name: Benchmark

on:
  workflow_dispatch:


permissions:
  checks: write
  contents: write

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: |
            ${{ runner.os }}-konan

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --parallel

      - run: make jacksonBenchmark-linux

      - uses: actions/upload-artifact@v4
        with:
          name: profile-results
          path: profile-results/**
