name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: write

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: |
            ${{ runner.os }}-konan

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --parallel
          dependency-graph: generate-and-submit

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          include_passed: true
          detailed_summary: true
          report_paths: '**/build/test-results/*/TEST-*.xml'
