name: Publish kotlinx-serialization-smile-core

on:
  release:
    types: [published]

jobs:
  publish:

    strategy:
      matrix:
        include:
          - target: publishAllPublicationsToMavenCentralRepository
            os: macos-latest
          - target: publishLinuxX64PublicationToMavenCentralRepository
            os: ubuntu-latest
          - target: publishMingwX64PublicationToMavenCentralRepository
            os: windows-latest

    runs-on: ${{ matrix.os }}

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
      TAG: ${{ github.event.release.tag_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: |
            ${{ runner.os }}-konan

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :kotlinx-serialization-smile-core:${{ matrix.target }} --no-configuration-cache
